import { MediaContent, Channel, SubtitleTrack, User, SubscriptionPlan, Coupon, PaymentTransaction } from './types';

export const CATEGORIES = ['All', 'Action', 'Drama', 'Comedy', 'Sci-Fi', 'Thriller', 'Animation', 'Romance', 'Documentary'];

export const INITIAL_PLANS: SubscriptionPlan[] = [
    {
        id: 'plan-1',
        name: '1 Month',
        price: 200,
        duration: '30 Days',
        features: ['HD Streaming', 'Mobile & PC', 'No Ads']
    },
    {
        id: 'plan-2',
        name: '2 Months',
        price: 400,
        duration: '60 Days',
        features: ['HD Streaming', 'Mobile & PC', 'No Ads', 'Offline Download']
    },
    {
        id: 'plan-3',
        name: '3 Months',
        price: 590,
        duration: '90 Days',
        features: ['4K Ultra HD', '3 Devices', 'Priority Support', 'Offline Download']
    },
    {
        id: 'plan-4',
        name: '1 Year',
        price: 1599,
        duration: '365 Days',
        features: ['4K Ultra HD', '5 Devices', 'VIP Access', 'Offline Download']
    }
];

export const INITIAL_COUPONS: Coupon[] = [
    { id: 'c1', code: 'SUMON20', discountAmount: 20, isActive: true },
    { id: 'c2', code: 'EID50', discountAmount: 50, isActive: false }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'admin-1',
    name: 'Admin User',
    email: 'admin@sumonflix.net',
    isPremium: true,
    isAdmin: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
    deviceInfo: {
        model: 'iPhone 14 Pro Max',
        os: 'iOS 17.2',
        ip: '192.168.1.1',
        permissions: { camera: true, gallery: true, microphone: true }
    },
    paymentDetails: {
        accountNumber: '01700000000',
        transactionId: 'TRX789456123',
        method: 'bKash',
        lastPaymentDate: new Date('2023-12-01')
    }
  },
  {
    id: 'user-1',
    name: 'Demo User',
    email: 'user@sumonflix.net',
    isPremium: false,
    isAdmin: false,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user',
    deviceInfo: {
        model: 'Samsung Galaxy S23',
        os: 'Android 14',
        ip: '192.168.1.5',
        permissions: { camera: true, gallery: false, microphone: false }
    }
  }
];

export const INITIAL_TRANSACTIONS: PaymentTransaction[] = [
    {
        id: 'trx-1',
        userId: 'user-1',
        userName: 'Demo User',
        userEmail: 'user@sumonflix.net',
        bkashNumber: '01798765432',
        trxId: 'TXN_PENDING_001',
        plan: '1 Month',
        amount: '200',
        status: 'pending',
        date: new Date()
    },
    {
        id: 'trx-2',
        userId: 'admin-1',
        userName: 'Admin User',
        userEmail: 'admin@sumonflix.net',
        bkashNumber: '01700000000',
        trxId: 'TRX789456123',
        plan: '1 Year',
        amount: '1599',
        status: 'approved',
        date: new Date('2023-12-01')
    }
];

export const MOCK_CHANNELS: Channel[] = [
  {
    id: 'ch-1',
    name: 'GTV Live',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b3/Gazi_TV_logo.svg/1200px-Gazi_TV_logo.svg.png',
    currentProgram: 'Cricket Highlights',
    category: 'Sports',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    streamType: 'm3u8',
    isPremium: true
  },
  {
    id: 'ch-2',
    name: 'Somoy TV',
    logo: 'https://yt3.googleusercontent.com/ytc/AIdro_k6gC6o6v0G0y0s9z0b0l4l0d0j0g0h0j0k0l0=s900-c-k-c0x00ffffff-no-rj',
    currentProgram: 'Live News',
    category: 'News',
    streamUrl: 'https://www.youtube.com/embed/5geU6kZ8uK4',
    streamType: 'embed',
    isPremium: false
  },
  {
    id: 'ch-3',
    name: 'T-Sports',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/87/T_Sports_logo.png/220px-T_Sports_logo.png',
    currentProgram: 'Football Live',
    category: 'Sports',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    streamType: 'm3u8',
    isPremium: true
  },
  {
    id: 'ch-4',
    name: 'Channel I',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/69/Channel_i_logo.svg/1200px-Channel_i_logo.svg.png',
    currentProgram: 'Drama Serials',
    category: 'Entertainment',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    streamType: 'm3u8',
    isPremium: false
  }
];

export const MOCK_CONTENT: MediaContent[] = [
  {
    id: 'mov-2',
    title: 'The Lost Kingdom',
    description: 'An archaeologist finds a map to an ancient civilization hidden beneath the ocean, guarded by mystical creatures.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1000&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    category: 'Action',
    rating: 4.5,
    year: 2023,
    duration: '1h 55m',
    type: 'movie',
    isPremium: true
  },
  {
    id: 'mov-3',
    title: 'Midnight in Paris',
    description: 'A romantic tale of love and mystery set in the heart of France, where the past comes alive at midnight.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1000&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    category: 'Romance',
    rating: 4.2,
    year: 2022,
    duration: '1h 45m',
    type: 'movie',
    isPremium: false
  },
  {
     id: 'ser-1',
     title: 'Space Voyagers',
     description: 'A crew of astronauts explores the unknown reaches of the galaxy, encountering new civilizations and cosmic dangers.',
     thumbnailUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1000&q=80',
     videoUrl: '', // Series placeholder
     category: 'Sci-Fi',
     rating: 4.9,
     year: 2024,
     duration: '1 Season',
     type: 'series',
     isPremium: true,
     episodes: [
         {
             id: 'ep-1',
             title: 'Departure',
             description: 'The journey begins as the crew leaves Earth behind.',
             duration: '45m',
             thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1000&q=80',
             videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'
         },
         {
             id: 'ep-2',
             title: 'The Nebula',
             description: 'Strange signals are received from a nearby nebula.',
             duration: '42m',
             thumbnailUrl: 'https://images.unsplash.com/photo-1534972195531-d756b9bfa9f2?auto=format&fit=crop&w=1000&q=80',
             videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'
         }
     ]
  },
  {
      id: 'mov-4',
      title: 'Urban Legends',
      description: 'A documentary exploring the most chilling urban legends from around the world.',
      thumbnailUrl: 'https://images.unsplash.com/photo-1517502884422-41e157d44301?auto=format&fit=crop&w=1000&q=80',
      videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
      category: 'Documentary',
      rating: 4.6,
      year: 2023,
      duration: '1h 30m',
      type: 'movie',
      isPremium: false
  }
];

export const TRANSLATIONS = {
  en: {
    home: 'Home',
    liveTv: 'Live TV',
    movies: 'Movies',
    downloads: 'Downloads',
    search: 'Search',
    premium: 'Premium',
    admin: 'Admin Panel',
    logOut: 'Log Out',
    theme: 'Theme',
    language: 'Language',
    featured: 'Featured',
    watchNow: 'Watch Now',
    moreInfo: 'More Info',
    recommended: 'Recommended For You',
    liveTvGuide: 'Live TV Guide',
    addStream: 'Add Stream',
    noChannels: 'No channels found in this category.',
    addLiveStream: 'Add Live Stream',
    pasteLink: 'Paste your M3U8, YouTube, or Embed link.',
    channelName: 'Channel Name',
    streamUrl: 'Stream URL',
    supports: 'Supports: .m3u8, .ts, YouTube, Embed links',
    category: 'Category',
    type: 'Type',
    autoDetect: 'Auto-Detect',
    addChannel: 'Add Channel',
    resultsFor: 'Results for',
    noResults: 'No matching results found.',
    trySearching: 'Try searching for a different title or channel.',
    popularCategories: 'Popular Categories',
    premiumFeatures: 'Premium Features',
    upgradeText: 'Upgrade to Sumonflix Premium and unlock a world of entertainment. Enjoy exclusive benefits tailored just for you.',
    liveTvChannels: 'Live TV Channels',
    liveTvDesc: 'Access exclusive local & international channels.',
    adFree: 'Ad-Free Streaming',
    adFreeDesc: 'Enjoy movies and shows without interruptions.',
    ultraHd: '4K Ultra HD',
    ultraHdDesc: 'Crystal clear quality on all your devices.',
    offlineViewing: 'Offline Viewing',
    offlineDesc: 'Download your favorites to watch anywhere.',
    choosePlan: 'Choose Your Plan',
    monthly: 'Monthly',
    month: 'Month',
    subscribeNow: 'Subscribe Now',
    standard: 'Standard',
    months: 'Months',
    quarterly: 'Quarterly',
    bestValue: 'BEST VALUE',
    saveInstantly: 'Save 20৳ instantly',
    howToPay: 'How to Pay',
    bkashInstruction: 'Use bKash "Send Money" (Personal) to activate your subscription instantly.',
    personalNumber: 'Personal Account Number',
    copyNumber: 'Copy Number',
    activeReady: 'Active & Ready to Receive',
    castCrew: 'Cast & Crew',
    play: 'Play',
    download: 'Download',
    downloading: 'Downloading...',
    downloaded: 'Downloaded',
    removeFromDownloads: 'Remove',
    noDownloads: 'No downloaded content yet.',
    rating: 'Rating',
    releaseYear: 'Release Year',
    duration: 'Duration',
    genre: 'Genre',
    episodes: 'Episodes',
    youMayLike: 'You May Also Like',
    about: 'About',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    createAccount: 'Create Account',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    fullName: 'Full Name',
    coverName: 'Cover Name (Optional)',
    profilePhoto: 'Profile Photo URL (Optional)',
    emailAddress: 'Email Address',
    password: 'Password',
    welcomeBack: 'Welcome Back',
    gateway: 'Your gateway to unlimited entertainment',
    nowPlaying: 'Now Playing',
    movie: 'Movie',
    series: 'Series',
    help: 'Help',
    officialContact: 'Official Contact',
    address: 'Address',
    phone: 'Phone',
    email: 'Email',
    visitPage: 'Visit Page',
    callNow: 'Call Now',
    facebook: 'Facebook Page',
    dashboard: 'Dashboard',
    manageContent: 'Manage Content',
    manageChannels: 'Manage Channels',
    manageUsers: 'Manage Users',
    manageInbox: 'Support Inbox',
    settings: 'Settings',
    totalUsers: 'Total Users',
    totalMovies: 'Total Movies',
    totalChannels: 'Total Channels',
    revenue: 'Revenue (Est.)',
    actions: 'Actions',
    addContent: 'Add Content',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    save: 'Save',
    notify: 'Notify',
    sendNotification: 'Send Notification',
    notificationMessage: 'Notification Message',
    send: 'Send',
    changePassword: 'Change Password',
    newPassword: 'New Password',
    update: 'Update',
    logoUpload: 'Direct Gallery Photos Add',
    logoUrl: 'Or Logo URL',
    notifications: 'Notifications',
    noNotifications: 'No new notifications.',
    adminReply: 'Admin Reply',
    typeReply: 'Type your reply...',
    adminSettings: 'Admin Settings',
    replyToUser: 'Reply to User',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    enterNewPassword: 'Enter New Password',
    backToLogin: 'Back to Login',
    passwordResetSuccess: 'Password reset successfully!',
    updatePassword: 'Update Password'
  },
  bn: {
    home: 'হোম',
    liveTv: 'লাইভ টিভি',
    movies: 'সিনেমা',
    downloads: 'ডাউনলোড',
    search: 'অনুসন্ধান',
    premium: 'প্রিমিয়াম',
    admin: 'অ্যাডমিন প্যানেল',
    logOut: 'লগ আউট',
    theme: 'থিম',
    language: 'ভাষা',
    featured: 'ফিচারড',
    watchNow: 'এখনই দেখুন',
    moreInfo: 'আরও তথ্য',
    recommended: 'আপনার জন্য প্রস্তাবিত',
    liveTvGuide: 'লাইভ টিভি গাইড',
    addStream: 'স্ট্রিম যোগ করুন',
    noChannels: 'এই ক্যাটাগরিতে কোনো চ্যানেল পাওয়া যায়নি।',
    addLiveStream: 'লাইভ স্ট্রিম যোগ করুন',
    pasteLink: 'আপনার M3U8, YouTube, বা Embed লিঙ্ক পেস্ট করুন।',
    channelName: 'চ্যানেলের নাম',
    streamUrl: 'স্ট্রিম ইউআরএল',
    supports: 'সাপোর্ট করে: .m3u8, .ts, YouTube, Embed লিঙ্ক',
    category: 'ক্যাটাগরি',
    type: 'টাইপ',
    autoDetect: 'অটো-ডিটেক্ট',
    addChannel: 'চ্যানেল যোগ করুন',
    resultsFor: 'ফলাফল:',
    noResults: 'কোনো ফলাফল পাওয়া যায়নি।',
    trySearching: 'ভিন্ন নাম বা চ্যানেল দিয়ে চেষ্টা করুন।',
    popularCategories: 'জনপ্রিয় ক্যাটাগরি',
    premiumFeatures: 'প্রিমিয়াম ফিচার',
    upgradeText: 'সুমনফ্লিক্স প্রিমিয়ামে আপগ্রেড করুন এবং বিনোদনের দুনিয়া আনলক করুন।',
    liveTvChannels: 'লাইভ টিভি চ্যানেল',
    liveTvDesc: 'এক্সক্লুসিভ লোকাল এবং আন্তর্জাতিক চ্যানেল।',
    adFree: 'বিজ্ঞাপন-মুক্ত স্ট্রিমিং',
    adFreeDesc: 'বিরতিহীন সিনেমা এবং শো উপভোগ করুন।',
    ultraHd: '4K আল্ট্রা এইচডি',
    ultraHdDesc: 'সব ডিভাইসে ক্রিস্টাল ক্লিয়ার কোয়ালিটি।',
    offlineViewing: 'অফলাইন ভিউইং',
    offlineDesc: 'যেকোনো জায়গায় দেখতে ডাউনলোড করুন।',
    choosePlan: 'আপনার প্ল্যান বেছে নিন',
    monthly: 'মাসিক',
    month: 'মাস',
    subscribeNow: 'সাবস্ক্রাইব করুন',
    standard: 'স্ট্যান্ডার্ড',
    months: 'মাস',
    quarterly: 'ত্রৈমাসিক',
    bestValue: 'সেরা অফার',
    saveInstantly: '২০৳ সেভ করুন',
    howToPay: 'কিভাবে পেমেন্ট করবেন',
    bkashInstruction: 'সাবস্ক্রিপশন চালু করতে বিকাশ "সেন্ড মানি" (পার্সোনাল) ব্যবহার করুন।',
    personalNumber: 'পার্সোনাল অ্যাকাউন্ট নম্বর',
    copyNumber: 'নম্বর কপি করুন',
    activeReady: 'সক্রিয় এবং গ্রহণে প্রস্তুত',
    castCrew: 'কলাকুশলী',
    play: 'প্লে',
    download: 'ডাউনলোড',
    downloading: 'ডাউনলোড হচ্ছে...',
    downloaded: 'ডাউনলোড সম্পন্ন',
    removeFromDownloads: 'মুছে ফেলুন',
    noDownloads: 'কোনো ডাউনলোড করা কন্টেন্ট নেই।',
    rating: 'রেটিং',
    releaseYear: 'মুক্তির বছর',
    duration: 'সময়কাল',
    genre: 'জনরা',
    episodes: 'পর্বসমূহ',
    youMayLike: 'আপনার পছন্দ হতে পারে',
    about: 'সম্পর্কে',
    signIn: 'সাইন ইন',
    signUp: 'সাইন আপ',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    dontHaveAccount: "অ্যাকাউন্ট নেই?",
    alreadyHaveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    fullName: 'পুরো নাম',
    coverName: 'কভার নাম (ঐচ্ছিক)',
    profilePhoto: 'প্রোফাইল ছবি ইউআরএল (ঐচ্ছিক)',
    emailAddress: 'ইমেইল ঠিকানা',
    password: 'পাসওয়ার্ড',
    welcomeBack: 'স্বাগতম',
    gateway: 'আনলিমিটেড বিনোদনের দুনিয়া',
    nowPlaying: 'এখন চলছে',
    movie: 'সিনেমা',
    series: 'সিরিজ',
    help: 'সাহায্য',
    officialContact: 'অফিসিয়াল যোগাযোগ',
    address: 'ঠিকানা',
    phone: 'ফোন',
    email: 'ইমেইল',
    visitPage: 'ভিজিট করুন',
    callNow: 'কল করুন',
    facebook: 'ফেসবুক পেজ',
    dashboard: 'ড্যাশবোর্ড',
    manageContent: 'কন্টেন্ট ম্যানেজমেন্ট',
    manageChannels: 'চ্যানেল ম্যানেজমেন্ট',
    manageUsers: 'ব্যবহারকারী ম্যানেজমেন্ট',
    manageInbox: 'সাপোর্ট ইনবক্স',
    settings: 'সেটিংস',
    totalUsers: 'মোট ব্যবহারকারী',
    totalMovies: 'মোট সিনেমা',
    totalChannels: 'মোট চ্যানেল',
    revenue: 'আয় (আনুমানিক)',
    actions: 'অ্যাকশন',
    addContent: 'কন্টেন্ট যোগ করুন',
    edit: 'এডিট',
    delete: 'ডিলিট',
    cancel: 'বাতিল',
    save: 'সংরক্ষণ',
    notify: 'নোটিফিকেশন',
    sendNotification: 'নোটিফিকেশন পাঠান',
    notificationMessage: 'বার্তা লিখুন',
    send: 'পাঠান',
    changePassword: 'পাসওয়ার্ড পরিবর্তন',
    newPassword: 'নতুন পাসওয়ার্ড',
    update: 'আপডেট',
    logoUpload: 'গ্যালারি থেকে লোগো যোগ করুন',
    logoUrl: 'অথবা লোগো ইউআরএল',
    notifications: 'নোটিফিকেশন',
    noNotifications: 'কোনো নতুন নোটিফিকেশন নেই।',
    adminReply: 'অ্যাডমিন রিপ্লাই',
    typeReply: 'আপনার উত্তর লিখুন...',
    adminSettings: 'অ্যাডমিন সেটিংস',
    replyToUser: 'ব্যবহারকারীকে উত্তর দিন',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    resetPassword: 'পাসওয়ার্ড রিসেট করুন',
    enterNewPassword: 'নতুন পাসওয়ার্ড দিন',
    backToLogin: 'লগিনে ফিরে যান',
    passwordResetSuccess: 'পাসওয়ার্ড সফলভাবে রিসেট হয়েছে!',
    updatePassword: 'পাসওয়ার্ড আপডেট করুন'
  }
};